server:
  port: 8181
#  context-path: /myboot

logging:
  path: /F:/myboot_log
  level: info

spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password:
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    pool:
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username:
    password:
#  mvc:
#    view:
#      suffix: .html
#      prefix: /



mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.sym.myboot.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


